services:
  app:
    build: .
    container_name: akaunting_app
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: akaunting_db
    environment:
      MYSQL_DATABASE: akaunting
      MYSQL_USER: akaunting
      MYSQL_PASSWORD: akaunting
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

