apiVersion: v1
kind: Secret
metadata:
  name: akaunting-secret
  namespace: akaunting
type: Opaque
stringData:
  APP_KEY: "base64:B1DqwDxbX+b5a24tyy1WHl5jAI3v0qPhnKGuomBI+0Y="
  DB_PASSWORD: "akauntingpass"
