apiVersion: v1
kind: ConfigMap
metadata:
  name: akaunting-config
  namespace: akaunting
data:
  APP_NAME: "Akaunting"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://localhost"
  
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "akaunting"
  DB_USERNAME: "akaunting"
  
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "error"
